name: Build Vue and Deploy Node App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Install frontend dependencies
        working-directory: ./frontapp
        run: npm ci

      - name: Build Vue app
        working-directory: ./frontapp
        run: npm run build
        
      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/project_node
            git pull origin main
            npm install --prefix backend
            pm2 restart app || pm2 start backend/app.js --name "app"
            pm2 save
          EOF
